COG_COLORS = {
    'C': '#A6CEE3', 
    'D': '#1F78B4', 
    'E': '#B2DF8A', 
    'F': '#33A02C', 
    'G': '#FB9A99', 
    'H': '#E31A1C', 
    'I': '#FDBF6F', 
    'J': '#FF7F00', 
    'K': '#CAB2D6', 
    'L': '#6A3D9A', 
    'M': '#FFFF99', 
    'N': '#E6AB02', 
    'O': '#8bc5c5', 
    'P': '#1B9E77', 
    'Q': '#dca7c2', 
    'R': '#E7298A', 
    'S': '#d3d3d3', 
    'T': '#f2c36e', 
    'U': '#A6761D', 
    'V': '#7cb9cb', 
    'W': '#5e79b2', 
    'X': '#773a27', 
    'Y': '#c29545', 
    'Z': '#60c86c', 
    'No Annotation': '#343438', 
}

COG_LABELS = {
    'C': 'C (Energy production and conversion)', 
    'D': 'D (Cell cycle control, cell division, chromosome partitioning)', 
    'E': 'E (Amino acid transport and metabolism)', 
    'F': 'F (Nucleotide transport and metabolism)', 
    'G': 'G (Carbohydrate transport and metabolism)', 
    'H': 'H (Coenzyme transport and metabolism)', 
    'I': 'I (Lipid transport and metabolism)', 
    'J': 'J (Translation, ribosomal structure and biogenesis)', 
    'K': 'K (Transcription)', 
    'L': 'L (Replication, recombination and repair)', 
    'M': 'M (Cell wall/membrane/envelope biogenesis)', 
    'N': 'N (Cell motility)', 
    'O': 'O (Posttranslational modification, protein turnover, chaperones)', 
    'P': 'P (Inorganic ion transport and metabolism)', 
    'Q': 'Q (Secondary metabolites biosynthesis, transport and catabolism)', 
    'R': 'R (General function prediction only)', 
    'S': 'S (Function unknown)', 
    'T': 'T (Signal transduction mechanisms)', 
    'U': 'U (Intracellular trafficking, secretion, and vesicular transport)', 
    'V': 'V (Defense mechanisms)', 
    'W': 'W (Extracellular structures)', 
    'X': 'X (Mobilome: prophages, transposons)', 
    'Y': 'Y (Nuclear structure)', 
    'Z': 'Z (Cytoskeleton)', 
    'No Annotation': 'No COG Annotation', 
}